export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const GET_JOBS_START = "GET_JOBS_START";
export const GET_JOBS_SUCCESS = "GET_JOBS_START";

export const GET_JOB_BY_ID_START = "GET_JOBS_BY_ID_START";
export const GET_JOB_BY_ID_SUCCESS = "GET_JOBS_BY_ID_SUCCESS";

export const ADD_JOB_START = "ADD_JOB_START";
export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS";

export const UPDATE_JOB_START = "UPDATE_JOB_START";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";

export const DELETE_JOB_START = "DELETE_JOB_START";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";

export const GET_COMPANIES_START = "GET_COMPANIES_START";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_START";

export const GET_COMPANY_BY_ID_START = "GET_JOBS_BY_ID_START";
export const GET_COMPANY_BY_ID_SUCCESS = "GET_JOBS_BY_ID_SUCCESS";

export const UPDATE_COMPANY_START = "UPDATE_COMPANY_START";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";

export const DELETE_COMPANY_START = "DELETE_COMPANY_START";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";

export const GET_SEEKERS_START = "GET_SEEKERS_START";
export const GET_SEEKERS_SUCCESS = "GET_SEEKERS_START";

export const GET_SEEKER_BY_ID_START = "GET_SEEKERS_BY_ID_START";
export const GET_SEEKER_BY_ID_SUCCESS = "GET_SEEKERS_BY_ID_SUCCESS";

export const UPDATE_SEEKER_START = "UPDATE_SEEKER_START";
export const UPDATE_SEEKER_SUCCESS = "UPDATE_SEEKER_SUCCESS";

export const DELETE_SEEKER_START = "DELETE_SEEKER_START";
export const DELETE_SEEKER_SUCCESS = "DELETE_SEEKER_SUCCESS";

export const GET_SAVED_COMPANIES_START = "GET_SAVED_START";
export const GET_SAVED_COMPANIES_SUCCESS = "GET_SAVED_START";

export const GET_SAVED_COMPANY_BY_ID_START = "GET_SAVED_BY_ID_START";
export const GET_SAVED_COMPANY_BY_ID_SUCCESS = "GET_SAVED_BY_ID_SUCCESS";

export const GET_SAVED_SEEKERS_START = "GET_SAVED_START";
export const GET_SAVED_SEEKERS_SUCCESS = "GET_SAVED_START";

export const GET_SAVED_SEEKER_BY_ID_START = "GET_SAVED_START";
export const GET_SAVED_SEEKER_BY_ID_SUCCESS = "GET_SAVED_START";

export const ADD_SAVED_START = "ADD_SAVED_START";
export const ADD_SAVED_SUCCESS = "ADD_SAVED_SUCCESS";

export const DELETE_SAVED_COMPANY_START = "DELETE_SAVED_START";
export const DELETE_SAVED_COMPANY_SUCCESS = "DELETE_SAVED_SUCCESS";

export const DELETE_SAVED_SEEKER_START = "DELETE_SAVED_START";
export const DELETE_SAVED_SEEKER_SUCCESS = "DELETE_SAVED_SUCCESS";

export const FAILURE = "FAILURE";
