export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const GET_JOBS_START = "GET_JOBS_START";
export const GET_JOBS_SUCCESS = "GET_JOBS_START";

export const ADD_JOBS_START = "ADD_JOB_START";
export const ADD_JOBS_SUCCESS = "ADD_JOB_SUCCESS";

export const UPDATE_JOBS_START = "UPDATE_JOB_START";
export const UPDATE_JOBS_SUCCESS = "UPDATE_JOB_SUCCESS";

export const DELETE_JOBS_START = "DELETE_JOB_START";
export const DELETE_JOBS_SUCCESS = "DELETE_JOB_SUCCESS";

export const GET_COMPANIES_START = "GET_COMPANIES_START";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_START";

export const ADD_COMPANIES_START = "ADD_COMPANIES_START";
export const ADD_COMPANIES_SUCCESS = "ADD_COMPANIES_SUCCESS";

export const UPDATE_COMPANIES_START = "UPDATE_COMPANIES`_START";
export const UPDATE_COMPANIES_SUCCESS = "UPDATE_COMPANIES`_SUCCESS";

export const DELETE_COMPANIES_START = "DELETE_COMPANIES_START";
export const DELETE_COMPANIES_SUCCESS = "DELETE_COMPANIES_SUCCESS";
export const FAILURE = "FAILURE";
