import { axiosWithAuth } from "../../utils/axiosWithAuth";

import {
  GET_COMPANIES_START,
  GET_COMPANIES_SUCCESS,
  ADD_COMPANIES_START,
  ADD_COMPANIES_SUCCESS,
  UPDATE_COMPANIES_START,
  UPDATE_COMPANIES_SUCCESS,
  DELETE_COMPANIES_START,
  DELETE_COMPANIES_SUCCESS,
  FAILURE
} from "./actions/__action-types";
