import axios from "axios";
import { axiosWithAuth } from "../../../utils/axiosWithAuth";

export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const GET_JOBS_START = "GET_JOBS_START";
export const GET_JOBS_SUCCESS = "GET_JOBS_START";
export const GET_JOBS_FAILURE = "GET_JOBS_START";

export const ADD_JOB_START = "ADD_JOB_START";
export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS";
export const ADD_JOB_FAILURE = "ADD_JOB_FAILURE";

export const UPDATE_JOB_START = "UPDATE_JOB_START";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_FAILURE = "UPDATE_JOB_FAILURE";

export const DELETE_JOB_START = "DELETE_JOB_START";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAILURE = "DELETE_JOB_FAILURE";

export const GET_COMPANIES_START = "GET_JOBS_START";
export const GET_COMPANIES_SUCCESS = "GET_JOBS_START";
export const GET_COMPANIES_FAILURE = "GET_JOBS_START";

export const ADD_COMPANIES_START = "ADD_JOB_START";
export const ADD_COMPANIES_SUCCESS = "ADD_JOB_SUCCESS";
export const ADD_COMPANIES_FAILURE = "ADD_JOB_FAILURE";

export const UPDATE_COMPANIES_START = "UPDATE_JOB_START";
export const UPDATE_COMPANIES_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_COMPANIES_FAILURE = "UPDATE_JOB_FAILURE";

export const DELETE_COMPANIES_START = "DELETE_JOB_F";
export const DELETE_COMPANIES_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_COMPANIES_FAILURE = "DELETE_JOB_FAILURE";

export const DELETE_COMPANIES_START = "DELETE_JOB_F";
export const DELETE_COMPANIES_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_COMPANIES_FAILURE = "DELETE_JOB_FAILURE";
